version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: board
    volumes:
      - "mysqldata:/var/lib/mysql"
    networks:
      - msa

  board:
    build:
      context: ./AP_Detailpage
      dockerfile: Dockerfile
    container_name: detail_page
    command: ./wait-for-it.sh -t 15 mysql:3306 -- gradle bootRun
    restart: on-failure
    ports:
      - 8182:8182
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ce?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234